// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:bloc_app/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AirQualityConcUnitsAdapter());
    registerAdapter(CurrentPollutantModelAdapter());
    registerAdapter(CurrentWeatherVariableModelAdapter());
    registerAdapter(HourlyWeatherForecastModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AirQualityConcUnitsAdapter());
    registerAdapter(CurrentPollutantModelAdapter());
    registerAdapter(CurrentWeatherVariableModelAdapter());
    registerAdapter(HourlyWeatherForecastModelAdapter());
  }
}
